[package]
name = "common"
version = "0.1.0"
links = "marketmaker-mainnet-lib"
edition = "2018"

[features]
native = [
  "hyper", "hyper-rustls", "libc", "ring", "tokio", "tokio-core"
]

w-bindgen = ["wasm-bindgen", "web-sys"]

[lib]
name = "common"
path = "common.rs"
doctest = false

[dependencies]
arrayref = "0.3"
atomic = "0.4"
backtrace = "0.3"
base64 = "0.10.0"
bigdecimal = { version = "0.1", features = ["serde"] }
bitcrypto = { git = "https://github.com/artemii235/parity-bitcoin.git" }
bytes = "0.4"
# Using the `chrono` because the `time` formatting has serious limits, like the lack of subsecond support, IIRC.
chrono = "0.4"
crossbeam = "0.7"
findshlibs = "0.5"
fomat-macros = "0.2"
futures01 = { version = "0.1", package = "futures" }
futures = { version = ">=0.3.0-alpha.16, <0.4", package = "futures-preview", features = ["compat", "async-await", "nightly"] }
futures-cpupool = "0.1"
gstuff = { version = "0.6", features = ["nightly"] }
hdrhistogram = "7.0"
hex = "0.3.2"
http = "0.1"
http-body = "0.1"
hyper = { version = "0.12", optional = true }
hyper-rustls = { version = "0.16", optional = true }
itertools = "0.8"
keys = { git = "https://github.com/artemii235/parity-bitcoin.git" }
lazy_static = "1.2"
libc = { version = "0.2", optional = true }
metrics = "0.12"
metrics-runtime = {version = "0.13", default-features = false, features = ["metrics-observer-prometheus"] }
metrics-core = "0.5"
metrics-util = "0.3"
num-bigint = { version = "0.2", features = ["serde", "std"] }
num-rational = { version = "0.2", features = ["serde", "bigint", "bigint-std"] }
num-traits = "0.2"
parking_lot = { version = "0.7", features = ["nightly"] }
parking_lot_core = { version = "0.6", features = ["nightly"] }
primitives = { git = "https://github.com/artemii235/parity-bitcoin.git" }
rand = { version = "0.7", features = ["std", "small_rng"] }
regex = "1"
# To build `ring` on Windows we might need `perl` and `yasm` in the PATH
# (though I haven't checked this in a while).
# Download http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe and rename to `yasm.exe`.
ring = { version = "0.14", optional = true }
serde = "1"
serde_bencode = "0.2"
serde_bytes = "0.11"
serde_derive = "1"
serde_json = "1"
term = "0.5"
tokio = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
unwrap = "1.2"
uuid = { version = "0.7", features = ["serde", "v4"] }
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize", "nightly"], optional = true }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
]
optional = true

[build-dependencies]
bindgen = "0.43"
bzip2 = "0.3"
cc = "1.0"
chrono = "0.4"
fomat-macros = "0.3"
futures01 = { version = "0.1", package = "futures" }
futures-cpupool = "0.1"
glob = "0.3"
gstuff = { version = "0.6", features = ["nightly", "term"] }
hyper = "0.12"
hyper-rustls = "0.16"
libflate = "0.1"
num_cpus = "1.10"
regex = "1"
sysinfo = "0.9"
tar = "0.4"
unwrap = "1.2.1"
winapi = "0.3"
