[package]
name = "coins"
version = "0.1.0"
edition = "2018"

[features]
native = [
  "dirs", "rust-ini", "rustls", "tokio", "tokio-io", "tokio-rustls", "tokio-tcp", "webpki-roots",
  "common/native"
]

w-bindgen = ["common/w-bindgen", "js-sys", "wasm-bindgen", "wasm-bindgen-futures", "wasm-bindgen-test", "web-sys"]

[lib]
name = "coins"
path = "lp_coins.rs"
doctest = false

[dependencies]
base64 = "0.10.0"
dirs = { version = "1", optional = true }
bigdecimal = { version = "0.1.0", features = ["serde"] }
bitcrypto = { git = "https://github.com/artemii235/parity-bitcoin.git" }
byteorder = "1.3"
bytes = "0.4"
chain = { git = "https://github.com/artemii235/parity-bitcoin.git" }
common = { path = "../common" }
ethabi = { git = "https://github.com/artemii235/ethabi" }
ethcore-transaction = { git = "https://github.com/artemii235/parity-ethereum.git" }
ethereum-types = { version = "0.4", default-features = false, features = ["std", "serialize"] }
ethkey = { git = "https://github.com/artemii235/parity-ethereum.git" }
# Waiting for https://github.com/rust-lang/rust/issues/54725 to use on Stable.
#enum_dispatch = "0.1"
fomat-macros = "0.2"
futures01 = { version = "0.1", package = "futures" }
# using select macro requires the crate to be named futures, compilation failed with futures03 name
futures = { version = ">=0.3.0-alpha.16, <0.4", package = "futures-preview", features = ["compat", "async-await", "nightly"] }
futures-timer = "0.1"
gstuff = { version = "0.6", features = ["nightly"] }
hex = "0.3.2"
http = "0.1"
jsonrpc-core = "8.0.1"
keys = { git = "https://github.com/artemii235/parity-bitcoin.git" }
lazy_static = "1.3"
libc = "0.2"
libsecp256k1 = "0.2.2"
metrics = "0.12"
mocktopus = "0.7.0"
num-traits = "0.2"
primitives = { git = "https://github.com/artemii235/parity-bitcoin.git" }
rand = { version = "0.7", features = ["std", "small_rng"] }
rlp = { git = "https://github.com/artemii235/parity-common" }
rpc = { git = "https://github.com/artemii235/parity-bitcoin.git" }
rust-ini = { version = "0.13", optional = true }
rustls = { version = "0.15.2", features = ["dangerous_configuration"], optional = true }
script = { git = "https://github.com/artemii235/parity-bitcoin.git" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serialization = { git = "https://github.com/artemii235/parity-bitcoin.git" }
sha2 = "0.8"
sha3 = "0.8"
tokio = { version = "0.1", optional = true }
tokio-io = { version = "0.1.10"  , optional = true }
tokio-rustls = { version = "=0.9.1", optional = true }
tokio-tcp = { version = "0.1.4" , optional = true }
unwrap = "1.2"
# One of web3 dependencies is the old `tokio-uds 0.1.7` which fails cross-compiling to ARM.
# We don't need the default web3 features at all since we added our own web3 transport using shared HYPER instance.
web3 = { git = "https://github.com/artemii235/rust-web3", default-features = false }
webpki-roots = { version = "0.16.0", optional = true }
winapi = "0.3"

wasm-bindgen = { version = "0.2.50", features = ["serde-serialize", "nightly"], optional = true }
js-sys = { version = "0.3.27", optional = true }
wasm-bindgen-futures = { version = "0.4.1", optional = true }
wasm-bindgen-test = { version = "0.3.1", optional = true }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]
optional = true