name: atomicDex-API poist-release tests

on: push

jobs:

  dummy-job:
    name: Linux Check
    runs-on: self-hosted 

    steps:
     - uses: actions/checkout@v2

     - name: Install QT (Linux)
       uses: jurplel/install-qt-action@v2
       with:
         version: '5.14.1'
         host: 'linux'
         target: 'desktop'
         dir: '${{ github.workspace }}'
